# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/veux-dolby/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/veux-dolby

PRODUCT_COPY_FILES += \
    vendor/xiaomi/veux-dolby/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/xiaomi/veux-dolby/proprietary/vendor/etc/init/vendor.dolby.hardware.dms@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dolby.hardware.dms@2.0-service.rc

PRODUCT_PACKAGES += \
    libdapparamstorage \
    libdeccfg \
    libhwdap \
    libswgamedap \
    libswvqe \
    vendor.dolby.hardware.dms@2.0 \
    audio.primary.holi \
    libdlbdsservice \
    libstagefright_soft_ddpdec \
    libstagefrightdolby \
    vendor.dolby.hardware.dms@2.0-impl \
    manifest_vendor.dolby.hardware.dms.xml \
    vendor.dolby.hardware.dms@2.0-service
